using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestGeneratorLib
{
    internal class TestCreator
    {
        private CompilationUnitSyntax _test;
        private SyntaxNode _root;

        internal TestCreator(SyntaxNode root)
        {
            _root = root;
            _test = SyntaxFactory.CompilationUnit();
        }

        internal string GetTest()
        {
            var usings = _root.DescendantNodes().OfType<UsingDirectiveSyntax>().Select(us => us.Name.ToString()).ToArray();
            _test = _test.AddUsings(usings.Select(us => SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName(us))).ToArray());
            _test = _test.AddUsings(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("NUnit.Framework")));
            var namespaces = _root.DescendantNodes().OfType<NamespaceDeclarationSyntax>().ToArray();
            _test = _test.AddMembers(namespaces.Select(nm => CreateNamespace(nm)).ToArray());
            return _test.NormalizeWhitespace().ToFullString();
        }

        internal NamespaceDeclarationSyntax CreateNamespace(NamespaceDeclarationSyntax namespaceDeclaration)
        {
            var @namespace = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName(namespaceDeclaration.Name.ToString() + ".Tests"));
            var classes = namespaceDeclaration.DescendantNodes().OfType<ClassDeclarationSyntax>().ToArray();
            @namespace = @namespace.AddMembers(classes.Select(cl => CreateClass(cl)).ToArray());
            return @namespace;
        }

        internal ClassDeclarationSyntax CreateClass(ClassDeclarationSyntax classDeclaration)
        {
            var @class = SyntaxFactory.ClassDeclaration(classDeclaration.Identifier.ValueText + "Test")
                .WithAttributeLists(
                    SyntaxFactory.SingletonList(
                        SyntaxFactory.AttributeList(
                            SyntaxFactory.SingletonSeparatedList(
                                SyntaxFactory.Attribute(
                                    SyntaxFactory.IdentifierName("TestFixture"))))))
                 .WithModifiers(
                      SyntaxFactory.TokenList(
                          SyntaxFactory.Token(SyntaxKind.PublicKeyword)));
            var methods = classDeclaration.DescendantNodes().OfType<MethodDeclarationSyntax>().Where(mt => mt.Modifiers
                .Where(md => md.Kind().Equals(SyntaxKind.PublicKeyword) || md.Kind().Equals(SyntaxKind.InternalKeyword)).Any()).ToArray();
            @class = @class.AddMembers(methods.Select(mt => CreateTestMethod(mt)).ToArray());
            return @class;
        }

        internal MethodDeclarationSyntax CreateTestMethod(MethodDeclarationSyntax methodDeclaration)
        {
            var method = SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), methodDeclaration.Identifier.ValueText + "Test")
                .WithAttributeLists(
                    SyntaxFactory.SingletonList(
                        SyntaxFactory.AttributeList(
                            SyntaxFactory.SingletonSeparatedList(
                                SyntaxFactory.Attribute(
                                    SyntaxFactory.IdentifierName("Test"))))))
                .WithModifiers(
                     SyntaxFactory.TokenList(
                         SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                .WithBody(CreateTestMethodBody());
            return method;
        }

        internal BlockSyntax CreateTestMethodBody()
        {
            var body = SyntaxFactory.Block();
            var assertFunction = SyntaxFactory.ExpressionStatement(
                SyntaxFactory.InvocationExpression(
                SyntaxFactory.MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    SyntaxFactory.IdentifierName("Assert"),
                    SyntaxFactory.IdentifierName("Fail")))
                .WithArgumentList(SyntaxFactory.ArgumentList(
                        SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.Argument(
                                SyntaxFactory.LiteralExpression(
                                    SyntaxKind.StringLiteralExpression,
                                    SyntaxFactory.Literal("autogenerated"))))))
            );
            body = body.AddStatements(new[] { assertFunction });
            return body;
        }
    }
}
